### ISSUE TITLE
Stopped working completely while in the Garage Storage Area

### ISSUE THREAD

**Issue by ghost** [mannly01/TransferAll#19] opened 2024-04-05 11:13 UTC
Somehow this mod stopped working while inside the garage. Both keys still works fine in the scrapyard, I didn't test other locations as I assume they work too. But it does nothing anymore when you open the storage area in the garage and want to transfer items between inventory and storage.

Things I tried to do:
- Re-download the mod and reload a fresh (identical) config
- Test it with different types of new saves
- Test it with only this mod and no others to rule out conflicts
- Uninstalled MelonLoader, Steam verified gamefiles, Reinstall MelonLoader

None of these things changed anything, and the keys still don't work in the storage area. Could you please find a moment to look in to this? Thank you very much!

Edit to add that the logs show no errors, not upon loading the mod, and also not upon trying to use the keys.

**Comment by mannly01** [comment] 2024-04-06 04:02
Duplicate of #18.

**Comment by ghost** [comment] 2024-04-06 12:35
I saw that ticket before I opened this one, but I believe that is not the issue at hand. Because I have always had QoLMod installed and my console is not dropping any errors, which is the opposite of what #18 mentions. It just stopped working a couple of days ago. Maybe the easter update with all the eggs everywhere broke something?

**Comment by mannly01** [comment] 2024-04-06 13:46
You are correct. They changed some of the nomenclature for the Easter holiday. I'm working on a fix.

**Closed as completed** 2024-04-06 14:31 UTC
Labels: bug

**Comment by GermanioBR** [comment] 2024-04-20 12:02
This is still hapening.
I've tryied to download again, change the key bind for transfer and so on... nothing seens to work.
Tryied to change the MinNumOfItemsWarning and MinPartCondition too, but no success here.
As I can remember the only thing that I've changed in my game was downloading TKAftermarket and nothing more...
